# Generated by Django 5.1 on 2026-07-15 18:40

import common.models.ulid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(unique=True)),
                ('period_end', models.DateField()),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments_points_leaderboard_snapshot',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PointsEventRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('referral_success', 'Successful referral'), ('referred_first_order', "Referred user's first order"), ('order_streak_5', '5-order streak'), ('order_milestone_5', '5th order milestone (scratch card)'), ('order_rated', 'Order rated'), ('redemption', 'Points redeemed / withdrawn'), ('adjustment', 'Manual adjustment / reversal')], max_length=32, unique=True)),
                ('points_value', models.PositiveIntegerField(blank=True, null=True)),
                ('min_points', models.PositiveIntegerField(blank=True, null=True)),
                ('max_points', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments_points_event_rule',
            },
        ),
        migrations.CreateModel(
            name='PointsLedgerEntry',
            fields=[
                ('id', common.models.ulid.ULIDField(default=common.models.ulid.generate_ulid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('referral_success', 'Successful referral'), ('referred_first_order', "Referred user's first order"), ('order_streak_5', '5-order streak'), ('order_milestone_5', '5th order milestone (scratch card)'), ('order_rated', 'Order rated'), ('redemption', 'Points redeemed / withdrawn'), ('adjustment', 'Manual adjustment / reversal')], max_length=32)),
                ('points', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('proof_object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('idempotency_key', models.CharField(max_length=150, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proof_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_points_ledger_entry',
            },
        ),
        migrations.CreateModel(
            name='PointsWithdrawalRequest',
            fields=[
                ('id', common.models.ulid.ULIDField(default=common.models.ulid.generate_ulid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('points_requested', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='points.pointsledgerentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyLeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='points.monthlyleaderboardsnapshot')),
            ],
            options={
                'db_table': 'payments_points_leaderboard_entry',
                'ordering': ['rank'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'user'), name='uniq_leaderboard_snapshot_user')],
            },
        ),
        migrations.AddIndex(
            model_name='pointsledgerentry',
            index=models.Index(fields=['user', 'created_at'], name='payments_po_user_id_464647_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsledgerentry',
            index=models.Index(fields=['event_type'], name='payments_po_event_t_89d6cd_idx'),
        ),
    ]
