# Generated by Django 5.1 on 2026-08-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointseventrule',
            name='event_type',
            field=models.CharField(choices=[('referral_success', 'Successful referral'), ('referred_first_order', "Referred user's first order"), ('order_streak_5', '5-order streak'), ('order_milestone_5', '5th order milestone (scratch card)'), ('order_rated', 'Order rated'), ('order_payment', 'Order paid with points'), ('redemption', 'Points redeemed / withdrawn'), ('adjustment', 'Manual adjustment / reversal'), ('refund_compensation', 'Refund compensation points')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='pointsledgerentry',
            name='event_type',
            field=models.CharField(choices=[('referral_success', 'Successful referral'), ('referred_first_order', "Referred user's first order"), ('order_streak_5', '5-order streak'), ('order_milestone_5', '5th order milestone (scratch card)'), ('order_rated', 'Order rated'), ('order_payment', 'Order paid with points'), ('redemption', 'Points redeemed / withdrawn'), ('adjustment', 'Manual adjustment / reversal'), ('refund_compensation', 'Refund compensation points')], max_length=32),
        ),
    ]
