# Generated by Django 5.1 on 2025-09-03 17:13

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0, srid=4326), geography=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['location'], name='addresses_a_locatio_1841dc_idx'),
        ),
    ]
