# Generated by Django 5.1 on 2025-12-14 00:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_drivercred_remove_branch_phone_number_and_more'),
        ('addresses', '0002_alter_address_address_alter_address_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('heading', models.FloatField(default=0, help_text='Bearing in degrees (0-360)')),
                ('speed', models.FloatField(default=0, help_text='Speed in km/h')),
                ('accuracy', models.FloatField(default=0, help_text='Accuracy in meters')),
                ('is_online', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='accounts.driverprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['location'], name='addresses_d_locatio_c22c2c_idx'), models.Index(fields=['is_online', 'last_updated'], name='addresses_d_is_onli_a65a05_idx')],
            },
        ),
    ]
