# Generated by Django 5.1 on 2026-02-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_driverlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, default='Home', max_length=50, null=True),
        ),
    ]
