# Generated by Django 5.1 on 2026-03-08 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Configs',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_date', models.DateField()),
                ('status', models.CharField(choices=[('clean', 'Clean'), ('mismatches_found', 'Mismatches Found'), ('error', 'Error')], max_length=50)),
                ('total_checked', models.IntegerField(default=0)),
                ('mismatches', models.IntegerField(default=0)),
                ('mismatch_details', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64)),
                ('actor_id', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'actor_id', 'key'), name='uniq_payment_idempotency_scope_actor_key')],
            },
        ),
        migrations.CreateModel(
            name='PaystackWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('event_id', models.CharField(blank=True, max_length=100)),
                ('event_hash', models.CharField(db_index=True, max_length=64)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField()),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_reason', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paystack Webhook Log',
                'constraints': [models.UniqueConstraint(fields=('event_hash',), name='uniq_paystack_event_hash'), models.UniqueConstraint(condition=models.Q(('event_id', ''), _negated=True), fields=('event_id',), name='uniq_paystack_event_id')],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paystack_access_code', models.CharField(blank=True, max_length=100)),
                ('total_amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('in_escrow', 'In Escrow'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=50)),
                ('split_snapshot', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('service_completed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_sales', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driven_sales', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('referral_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('business_owner', 'Business Owner'), ('referral', 'Referral'), ('platform', 'Platform')], max_length=50)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('reversal', 'Reversal')], max_length=50)),
                ('amount', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField()),
                ('row_hash', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending_batch', 'Pending Batch'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending_batch', max_length=50)),
                ('strategy', models.CharField(choices=[('batch', 'Batch'), ('realtime', 'Realtime')], default='batch', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('batch_date', models.DateField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('paystack_transfer_code', models.CharField(blank=True, max_length=100)),
                ('paystack_transfer_ref', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paystack_recipient_code', models.CharField(max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.ledgerentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'idempotency_key'), name='uniq_withdrawal_user_idem')],
            },
        ),
    ]
