# Generated by Django 5.1 on 2026-04-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_useraccount'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccount',
            table='payments_user_account',
        ),
    ]
