# Generated by Django 5.1 on 2026-05-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_feature_plan_subscription_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='audience',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business'), ('none', 'None')], db_index=True, max_length=20),
        ),
    ]
