# Generated by Django 5.1 on 2026-05-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_invoice_failure_reason_alter_plan_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='descriptions',
            field=models.TextField(default=''),
        ),
    ]
