# Generated by Django 5.1 on 2026-05-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_plan_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='descriptions',
            new_name='description',
        ),
    ]
