# Generated by Django 5.1 on 2026-06-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_rename_descriptions_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bank_card_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='bank_card_info',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
