# Generated by Django 5.1 on 2026-06-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_cardauthorization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='bank_card_expiry_date',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='bank_card_info',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardauthorization',
            name='authorization_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
