# Generated by Django 5.1 on 2026-07-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remove_useraccount_bank_card_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('supports_transfer', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('country', 'code'), name='unique_bank_per_country')],
            },
        ),
    ]
