# Generated by Django 5.1 on 2026-07-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='slug',
        ),
    ]
