# Generated by Django 5.1 on 2026-07-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_remove_bank_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
