# Generated by Django 5.1 on 2026-07-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_bank_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
