# Generated by Django 5.1 on 2026-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_bank_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bank_name',
            field=models.CharField(default='bank', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_bank_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='transaction_pin_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
