# Generated by Django 5.1 on 2026-08-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_useraccount_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_source',
            field=models.CharField(choices=[('points', 'Points'), ('paystack', 'Paystack')], default='paystack', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='responsible_party',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('driver', 'Driver'), ('platform', 'Platform')], max_length=30),
        ),
        migrations.AddField(
            model_name='sale',
            name='responsible_party_reason',
            field=models.TextField(blank=True),
        ),
    ]
