# Generated by Django 5.1.6 on 2026-03-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F, Q


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0037_profilebase_and_profile_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileReferral",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("reward_issued", models.BooleanField(default=False)),
                ("reward_issued_at", models.DateTimeField(blank=True, null=True)),
                ("referee_profile", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="referral_received", to="accounts.profilebase")),
                ("referee_user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="profile_referral_received", to=settings.AUTH_USER_MODEL)),
                ("referrer_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="referrals_made", to="accounts.profilebase")),
                ("referrer_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="profile_referrals_made", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="profilereferral",
            constraint=models.CheckConstraint(check=~Q(referrer_user=F("referee_user")), name="chk_profile_referral_no_self_user"),
        ),
        migrations.AddConstraint(
            model_name="profilereferral",
            constraint=models.CheckConstraint(check=~Q(referrer_profile=F("referee_profile")), name="chk_profile_referral_no_same_profile"),
        ),
        migrations.AddIndex(
            model_name="profilereferral",
            index=models.Index(fields=["referrer_profile", "created_at"], name="referrals_p_referr_18fe6f_idx"),
        ),
        migrations.AddIndex(
            model_name="profilereferral",
            index=models.Index(fields=["created_at"], name="referrals_p_created_3fa9e4_idx"),
        ),
    ]
