# Generated by Django 5.1 on 2026-03-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='profilereferral',
            new_name='referrals_p_referre_ae2e6f_idx',
            old_name='referrals_p_referr_18fe6f_idx',
        ),
        migrations.RenameIndex(
            model_name='profilereferral',
            new_name='referrals_p_created_94bf71_idx',
            old_name='referrals_p_created_3fa9e4_idx',
        ),
    ]
