# Generated by Django 5.1 on 2026-04-19 09:42

import authflow.services.model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_remove_businesspayoutaccount_account_name_and_more'),
        ('referrals', '0002_rename_referrals_p_referr_18fe6f_idx_referrals_p_referre_ae2e6f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralPayout',
            fields=[
                ('id', authflow.services.model.ULIDField(db_index=True, default=authflow.services.model.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('units_paid', models.IntegerField()),
                ('conversion_rate', models.IntegerField(default=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referral_snapshot', models.JSONField(blank=True, default=list)),
                ('snapshot_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='profilereferral',
            name='referrals_p_referre_ae2e6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='profilereferral',
            name='referrals_p_created_94bf71_idx',
        ),
        migrations.RenameField(
            model_name='profilereferral',
            old_name='reward_issued_at',
            new_name='consumed_at',
        ),
        migrations.RenameField(
            model_name='profilereferral',
            old_name='reward_issued',
            new_name='is_consumed',
        ),
        migrations.AlterField(
            model_name='profilereferral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='profilereferral',
            name='id',
            field=authflow.services.model.ULIDField(db_index=True, default=authflow.services.model.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='profilereferral',
            index=models.Index(fields=['referrer_user', 'converted_at'], name='referrals_p_referre_97cf41_idx'),
        ),
        migrations.AddIndex(
            model_name='profilereferral',
            index=models.Index(fields=['is_consumed'], name='referrals_p_is_cons_c573f9_idx'),
        ),
        migrations.AddField(
            model_name='referralpayout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_payouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
