# Generated by Django 5.1 on 2026-10-01 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_businessonboardstatus_checked'),
        ('referrals', '0003_referralpayout_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profilereferral',
            name='chk_profile_referral_no_same_profile',
        ),
        migrations.AddField(
            model_name='profilereferral',
            name='fraud_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profilereferral',
            name='fraud_status',
            field=models.CharField(choices=[('clean', 'Clean'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], db_index=True, default='clean', max_length=20),
        ),
        migrations.AddField(
            model_name='profilereferral',
            name='referee_device_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profilereferral',
            name='referee_ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profilereferral',
            name='referee_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver')], db_index=True, default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='profilereferral',
            name='referrer_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver')], db_index=True, default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilereferral',
            name='referee_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_received', to='accounts.profilebase'),
        ),
        migrations.AlterField(
            model_name='profilereferral',
            name='referrer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='accounts.profilebase'),
        ),
        migrations.AddIndex(
            model_name='profilereferral',
            index=models.Index(fields=['fraud_status'], name='referrals_p_fraud_s_af843b_idx'),
        ),
    ]
