# Generated by Django 5.1 on 2026-10-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_remove_profilereferral_chk_profile_referral_no_same_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilereferral',
            name='referee_profile',
        ),
        migrations.RemoveField(
            model_name='profilereferral',
            name='referrer_profile',
        ),
    ]
