# Generated by Django 5.1 on 2026-02-02 21:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0029_branch_avg_rating_branch_rating_count_and_more'),
        ('menu', '0010_remove_address_user_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint_type', models.CharField(blank=True, choices=[('COLD_FOOD', 'Cold food'), ('DIRTY_ENVIRONMENT', 'Unhygienic/dirty environment'), ('WRONG_ORDER', 'Wrong order'), ('DELAYED_PREPARATION', 'Slow service / delayed preparation'), ('RUDE_STAFF', 'Rude staff'), ('OTHER', 'Other')], help_text='Select a branch-related complaint reason if applicable.', max_length=40, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='accounts.branch')),
                ('order', models.ForeignKey(help_text='The order this rating belongs to (per-order experience).', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='menu.order')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_given', to='accounts.customerprofile')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='ratings_bra_created_02454f_idx'), models.Index(fields=['order', 'created_at'], name='ratings_bra_order_i_22ce7a_idx'), models.Index(fields=['branch', 'created_at'], name='ratings_bra_branch__e3c78a_idx'), models.Index(fields=['branch', 'stars'], name='ratings_bra_branch__5b9ca0_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'rater', 'branch'), name='unique_branch_rating_per_order')],
            },
        ),
        migrations.CreateModel(
            name='DriverRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint_type', models.CharField(blank=True, choices=[('LATE_DELIVERY', 'Late delivery'), ('RUDE_DRIVER', 'Rude driver'), ('UNSAFE_DRIVING', 'Unsafe driving'), ('WRONG_ADDRESS', 'Went to wrong address'), ('OTHER', 'Other')], help_text='Select a driver-related complaint reason if applicable.', max_length=40, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='accounts.driverprofile')),
                ('order', models.ForeignKey(help_text='The order this rating belongs to (per-order experience).', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='menu.order')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_given', to='accounts.customerprofile')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='ratings_dri_created_448dea_idx'), models.Index(fields=['order', 'created_at'], name='ratings_dri_order_i_e3830d_idx'), models.Index(fields=['driver', 'created_at'], name='ratings_dri_driver__b54251_idx'), models.Index(fields=['driver', 'stars'], name='ratings_dri_driver__cc93bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'rater', 'driver'), name='unique_driver_rating_per_order')],
            },
        ),
    ]
