# Generated by Django 5.1.6 on 2025-08-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_restaurant_remove_restaurantprofile_location_and_more'),
        ('menu', '0003_variantgroup_variantoption_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantProfile',
        ),
    ]
