# Generated by Django 5.1 on 2025-09-03 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_address_latitude_remove_address_longitude_and_more'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='addresses.address'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_customers', to='addresses.address'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='customers', to='addresses.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
