# Generated by Django 5.1 on 2025-09-19 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role_primaryagent_linkedstaff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryagent',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch'),
        ),
        migrations.AddConstraint(
            model_name='primaryagent',
            constraint=models.UniqueConstraint(fields=('branch',), name='unique_primary_agent_per_branch'),
        ),
    ]
