# Generated by Django 5.1 on 2025-12-13 17:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_primaryagent_branch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rating',
            name='complaint_type',
            field=models.CharField(blank=True, choices=[('LATE_DELIVERY', 'Late delivery'), ('RUDE_DRIVER', 'Rude driver'), ('UNSAFE_DRIVING', 'Unsafe driving'), ('WRONG_ADDRESS', 'Went to wrong address'), ('COLD_FOOD', 'Cold food'), ('DIRTY_ENVIRONMENT', 'Unhygienic/dirty environment'), ('WRONG_ORDER', 'Wrong order'), ('DELAYED_PREPARATION', 'Slow service / delayed preparation'), ('RUDE_STAFF', 'Rude staff'), ('OTHER', 'Other')], help_text='Select a complaint reason if applicable.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_ratings_received', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_ratings_received', to='accounts.driverprofile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='accounts.customerprofile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['created_at'], name='accounts_ra_created_3f94d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rated_branch__isnull', True), ('rated_driver__isnull', False)), models.Q(('rated_branch__isnull', False), ('rated_driver__isnull', True)), _connector='OR'), name='only_one_rating_target'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('rater', 'rated_driver'), name='unique_driver_rating'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('rater', 'rated_branch'), name='unique_branch_rating'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='updated_at',
        ),
    ]
