# Generated by Django 5.1 on 2025-12-14 00:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.contrib.gis.db import models as gis_models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_rating_unique_together_rating_complaint_type_and_more'),
        ('menu', '0008_payment_delete_driver_order_delivery_secret_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin', models.CharField(max_length=50)),
                ('driver_license', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='drivers/photos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='driver_license',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='nin',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='plate_number',
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='average_prep_time',
            field=models.IntegerField(default=30, help_text='Minutes'),
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_accepting_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='current_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_driver', to='menu.order'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='total_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # migrations.AlterField(
        #     model_name='branch',
        #     name='location',
        #     field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        # ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE accounts_branch DROP COLUMN IF EXISTS location;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE accounts_branch ADD COLUMN location geography(POINT,4326);",
                    reverse_sql="ALTER TABLE accounts_branch DROP COLUMN IF EXISTS location;",
                ),
            ],
            state_operations=[
                migrations.RemoveField(model_name="branch", name="location"),
                migrations.AddField(
                    model_name="branch",
                    name="location",
                    field=gis_models.PointField(
                        geography=True,
                        srid=4326,
                        null=True,
                        blank=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['location'], name='accounts_br_locatio_423379_idx'),
        ),
        migrations.AddField(
            model_name='drivercred',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='accounts.driverprofile'),
        ),
    ]
