# Generated by Django 5.1 on 2025-12-14 00:42

from django.db import migrations, models
from django.contrib.gis.db import models as gis_models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_drivercred_remove_branch_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # drop any old/bad column if it exists (bigint or anything)
                migrations.RunSQL(
                    sql="ALTER TABLE accounts_driverprofile DROP COLUMN IF EXISTS location;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # add the correct geography column
                migrations.RunSQL(
                    sql="ALTER TABLE accounts_driverprofile ADD COLUMN location geography(POINT,4326);",
                    reverse_sql="ALTER TABLE accounts_driverprofile DROP COLUMN IF EXISTS location;",
                ),
            ],
            state_operations=[
                # ONLY AddField, because state doesn't have it yet at 0012
                migrations.AddField(
                    model_name="driverprofile",
                    name="location",
                    field=gis_models.PointField(
                        geography=True,
                        srid=4326,
                        null=True,
                        blank=True,
                    ),
                ),
            ],
        ),
    ]
