# Generated by Django 5.1 on 2025-12-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_branch_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='location',
        ),
    ]
