# Generated by Django 5.1 on 2025-12-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_driverprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='current_order',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='last_location_update',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='total_deliveries',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='driver_license',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='nin',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='photo',
            field=models.ImageField(default=None, upload_to='drivers/photos/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='plate_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='DriverCred',
        ),
    ]
