# Generated by Django 5.1 on 2025-12-14 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_driverprofile_created_at_and_more'),
        ('menu', '0009_address_chatmessage_orderevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='driver_license',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='nin',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='plate_number',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='current_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_driver', to='menu.order'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='total_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DriverCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin', models.CharField(max_length=50)),
                ('driver_license', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='drivers/photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='accounts.driverprofile')),
            ],
        ),
    ]
