# Generated by Django 5.1 on 2025-12-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_driverprofile_driver_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
