# Generated by Django 5.1 on 2025-12-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_driverprofile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        migrations.AddField(
            model_name='branch',
            name='address2',
            field=models.CharField(default='', max_length=500),
        ),
    ]
