# Generated by Django 5.1 on 2025-12-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_branch_address_branch_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address2',
        ),
    ]
