# Generated by Django 5.1 on 2025-12-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_branch_address2_branch_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
    ]
