# Generated by Django 5.1 on 2025-12-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_branch_address'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='branch',
            name='accounts_br_locatio_423379_idx',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='location',
        ),
    ]
