# Generated by Django 5.1 on 2025-12-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_branch_location'),
        ('addresses', '0003_driverlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        # migrations.AddField(
        #     model_name='branch',
        #     name='phone_number',
        #     field=models.CharField(blank=True, max_length=20),
        # ),
        # migrations.AddField(
        #     model_name='branch',
        #     name='restaurant',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.restaurant'),
        # ),
        # migrations.AlterField(
        #     model_name='branch',
        #     name='location',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='addresses.address'),
        # ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['location'], name='accounts_br_locatio_a04fda_idx'),
        ),
    ]
