# Generated by Django 5.1 on 2025-12-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_branch_phone_number_branch_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='branch',
            name='accounts_br_locatio_a04fda_idx',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='location',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
