# Generated by Django 5.1 on 2025-12-14 13:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_branch_accounts_br_locatio_a04fda_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
