# Generated by Django 5.1 on 2025-12-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_branch_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='average_prep_time',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='is_accepting_orders',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='is_active',
        ),
    ]
