# Generated by Django 5.1 on 2025-12-14 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_branch_average_prep_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='average_prep_time',
            field=models.IntegerField(default=30, help_text='Minutes'),
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_accepting_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
