# Generated by Django 5.1 on 2026-02-02 21:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_branch_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='avg_rating',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='branch',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.restaurant'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='avg_rating',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
