# Generated by Django 5.1 on 2026-02-10 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_branch_avg_rating_branch_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.restaurant'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['location'], name='accounts_br_locatio_423379_idx'),
        ),
    ]
