# Generated by Django 5.1 on 2026-02-19 11:42

import django.db.models.deletion
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_branch_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('other', 'Other')], default='restaurant', max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('business_address', models.CharField(blank=True, default='', max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('business_image', models.ImageField(blank=True, null=True, upload_to='business/images/')),
                ('bn_number', models.CharField(blank=True, default='', max_length=100)),
                ('certification', models.FileField(blank=True, null=True, upload_to='business/certs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver'), ('buisnessstaff', 'BuisnessStaff'), ('businessadmin', 'BusinessAdmin')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.business'),
        ),
        migrations.CreateModel(
            name='BusinessAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='accounts.business')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCerd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('other', 'Other')], default='restaurant', max_length=120)),
                ('doc_type', models.CharField(choices=[('cac', 'CAC Document'), ('tax', 'Tax Document'), ('id', 'ID Document'), ('other', 'Other')], default='other', max_length=20)),
                ('business_doc', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(bucket_name='ovena-private-bucket', custom_domain=None, file_overwrite=False, location='private', querystring_auth=True), upload_to='business/docs/')),
                ('registered_business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_identification_number', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buiness', to='accounts.business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=120)),
                ('bvn_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('bvn_verification_ref', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='accounts.business')),
            ],
        ),
    ]
