# Generated by Django 5.1 on 2026-02-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_business_remove_branch_restaurant_alter_user_role_and_more'),
        ('coupons_discount', '0003_remove_coupons_restaurant_coupons_business'),
        ('menu', '0014_remove_baseitem_unique_name_per_restaurant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
