# Generated by Django 5.1 on 2026-02-21 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_delete_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='bn_number',
        ),
        migrations.RemoveField(
            model_name='business',
            name='certification',
        ),
        migrations.AddField(
            model_name='branch',
            name='delivery_method',
            field=models.CharField(choices=[('instant', 'Instant'), ('scheduled', 'Scheduled')], default='instant', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='final_order_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='pre_order_open_period',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscerd',
            name='bn_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='businesscerd',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cerd', to='accounts.business'),
        ),
        migrations.AlterField(
            model_name='businesscerd',
            name='business_type',
            field=models.CharField(choices=[('LLC', 'Limited Liability Company'), ('C', 'Corporations'), ('P', 'Partnerships '), ('SP', 'Sole Proprietorships')], default='restaurant', max_length=120),
        ),
        migrations.AlterField(
            model_name='primaryagent',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_agent', to='accounts.branch'),
        ),
        migrations.CreateModel(
            name='BranchOperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='accounts.branch')),
            ],
            options={
                'unique_together': {('branch', 'day')},
            },
        ),
    ]
