# Generated by Django 5.1 on 2026-02-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_business_bn_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspayoutaccount',
            old_name='bvn_last4',
            new_name='bvn',
        ),
    ]
