# Generated by Django 5.1 on 2026-02-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_rename_bvn_last4_businesspayoutaccount_bvn'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
