# Generated by Django 5.1 on 2026-02-28 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_business_onboarding_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivercred',
            name='driver_license',
        ),
        migrations.RemoveField(
            model_name='drivercred',
            name='nin',
        ),
        migrations.RemoveField(
            model_name='drivercred',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='drivercred',
            name='plate_number',
        ),
        migrations.RemoveField(
            model_name='drivercred',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='drivercred',
            name='bvn_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='drivercred',
            name='guarantor1_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='drivercred',
            name='guarantor1_phone',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='drivercred',
            name='guarantor2_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='drivercred',
            name='guarantor2_phone',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='drivercred',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='drivercred',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='drivercred',
            name='nin_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('na', 'Prefer not to say')], default='na', max_length=20),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='residential_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='drivercred',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_creds', to='accounts.driverprofile'),
        ),
        migrations.CreateModel(
            name='BusinessOnboardStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_step', models.IntegerField(choices=[(0, 'notStarted'), (1, 'phase1'), (2, 'phase2'), (3, 'phase3')], default=0)),
                ('is_onboarding_complete', models.BooleanField(default=False)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cerd', to='accounts.businessadmin')),
            ],
        ),
        migrations.CreateModel(
            name='DriverBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=160)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='accounts.driverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DriverOnboardingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_version', models.CharField(default='v1', max_length=20)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reviewer_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_submissions', to='accounts.driverprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_driver_onboardings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('time_mask', models.PositiveSmallIntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accounts.driverprofile')),
            ],
            options={
                'unique_together': {('driver', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('delivery_bag', 'Delivery Bag Photo'), ('profile_pic', 'Profile Picture'), ('selfie', 'Selfie Verification')], max_length=40)),
                ('file', models.ImageField(upload_to='drivers/docs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewer_note', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.driverprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['driver', 'doc_type', 'status'], name='accounts_dr_driver__ba5c63_idx')],
                'constraints': [models.UniqueConstraint(fields=('driver', 'doc_type'), name='uniq_driver_doc_type')],
            },
        ),
        migrations.CreateModel(
            name='DriverVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('nin', 'NIN'), ('bvn', 'BVN')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('provider_name', models.CharField(blank=True, max_length=60)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='accounts.driverprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('driver', 'verification_type'), name='uniq_driver_verification_type')],
            },
        ),
    ]
