# Generated by Django 5.1.6 on 2026-03-01

import random
import string
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _generate_code(existing_codes):
    alphabet = string.ascii_uppercase + string.digits
    for _ in range(20):
        candidate = "".join(random.choice(alphabet) for _ in range(8))
        if candidate not in existing_codes:
            existing_codes.add(candidate)
            return candidate
    raise RuntimeError("Unable to generate unique referral code during migration.")


def backfill_profile_base(apps, schema_editor):
    CustomerProfile = apps.get_model("accounts", "CustomerProfile")
    DriverProfile = apps.get_model("accounts", "DriverProfile")
    ProfileBase = apps.get_model("accounts", "ProfileBase")

    existing_codes = set(
        ProfileBase.objects.exclude(referral_code__isnull=True)
        .exclude(referral_code="")
        .values_list("referral_code", flat=True)
    )

    for customer in CustomerProfile.objects.select_related("user").all():
        code = getattr(customer, "referral_code", None)
        if not code:
            code = _generate_code(existing_codes)
        else:
            existing_codes.add(code)
        base = ProfileBase.objects.create(
            user_id=customer.user_id,
            profile_type="customer",
            referral_code=code,
        )
        customer.base_profile_id = base.id
        customer.save(update_fields=["base_profile"])

    for driver in DriverProfile.objects.select_related("user").all():
        code = _generate_code(existing_codes)
        base = ProfileBase.objects.create(
            user_id=driver.user_id,
            profile_type="driver",
            referral_code=code,
        )
        driver.base_profile_id = base.id
        driver.save(update_fields=["base_profile"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_remove_drivercred_driver_license_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileBase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("profile_type", models.CharField(choices=[("customer", "Customer"), ("driver", "Driver")], db_index=True, max_length=20)),
                ("referral_code", models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="profile_bases", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="profilebase",
            constraint=models.UniqueConstraint(fields=("user", "profile_type"), name="uniq_profilebase_user_type"),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="base_profile",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="customer_profile", to="accounts.profilebase"),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="base_profile",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="driver_profile", to="accounts.profilebase"),
        ),
        migrations.RunPython(backfill_profile_base, reverse_code=noop_reverse),
        migrations.RemoveField(
            model_name="customerprofile",
            name="referral_code",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="referred_by",
        ),
    ]
