# Generated by Django 5.1 on 2026-03-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_profilebase_and_profile_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='created_at',
        ),
    ]
