# Generated by Django 5.1.6 on 2026-03-01

import django.db.models.deletion
from django.db import migrations, models


def assert_profilebase_invariants(apps, schema_editor):
    CustomerProfile = apps.get_model("accounts", "CustomerProfile")
    DriverProfile = apps.get_model("accounts", "DriverProfile")

    missing_customer = CustomerProfile.objects.filter(base_profile__isnull=True).count()
    missing_driver = DriverProfile.objects.filter(base_profile__isnull=True).count()
    if missing_customer:
        raise RuntimeError(f"{missing_customer} customer profiles missing base_profile.")
    if missing_driver:
        raise RuntimeError(f"{missing_driver} driver profiles missing base_profile.")

    bad_customer_type = CustomerProfile.objects.exclude(base_profile__profile_type="customer").count()
    bad_driver_type = DriverProfile.objects.exclude(base_profile__profile_type="driver").count()
    if bad_customer_type:
        raise RuntimeError(f"{bad_customer_type} customer profiles linked to wrong ProfileBase.profile_type.")
    if bad_driver_type:
        raise RuntimeError(f"{bad_driver_type} driver profiles linked to wrong ProfileBase.profile_type.")

    bad_customer_user = CustomerProfile.objects.exclude(base_profile__user_id=models.F("user_id")).count()
    bad_driver_user = DriverProfile.objects.exclude(base_profile__user_id=models.F("user_id")).count()
    if bad_customer_user:
        raise RuntimeError(f"{bad_customer_user} customer profiles linked to ProfileBase of another user.")
    if bad_driver_user:
        raise RuntimeError(f"{bad_driver_user} driver profiles linked to ProfileBase of another user.")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0038_remove_customerprofile_created_at"),
    ]

    operations = [
        migrations.RunPython(assert_profilebase_invariants, reverse_code=noop_reverse),
        migrations.AlterField(
            model_name="customerprofile",
            name="base_profile",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="customer_profile", to="accounts.profilebase"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="base_profile",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="driver_profile", to="accounts.profilebase"),
        ),
    ]

