# Generated by Django 5.1.6 on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0039_profilebase_invariants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("driver", "Driver"),
                    ("businessstaff", "BusinessStaff"),
                    ("buisnessstaff", "BuisnessStaff (Legacy)"),
                    ("businessadmin", "BusinessAdmin"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]

