# Generated by Django 5.1 on 2026-03-01 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_user_role_choices_businessstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='base_profile',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='base_profile',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profilebase_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profilebase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='profilebase_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profilebase'),
            preserve_default=False,
        ),
    ]
