# Generated by Django 5.1 on 2026-03-02 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_remove_customerprofile_base_profile_and_more'),
        ('addresses', '0004_alter_address_label'),
        ('menu', '0014_remove_baseitem_unique_name_per_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profilebase_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='customer_profile', serialize=False, to='accounts.profilebase'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='profilebase_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='driver_profile', serialize=False, to='accounts.profilebase'),
        ),
    ]
