# Generated by Django 5.1 on 2026-03-05 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_customerprofile_profilebase_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessadmin',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='accounts.business'),
        ),
    ]
