# Generated by Django 5.1 on 2026-03-28 23:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryagent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primaryagent',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='linked_staff', to='accounts.businessadmin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primaryagent',
            name='device_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='primaryagent',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LinkedStaff',
        ),
    ]
