# Generated by Django 5.1 on 2026-03-29 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_primaryagent_created_at_primaryagent_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryagent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_staff', to='accounts.businessadmin', unique=True),
        ),
    ]
