# Generated by Django 5.1 on 2026-03-29 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_primaryagent_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryagent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_staff', to='accounts.businessadmin'),
        ),
        migrations.AlterField(
            model_name='primaryagent',
            name='device_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
