# Generated by Django 5.1 on 2026-04-10 13:35

from django.db import migrations, models


def copy_old_bank_fields(apps, schema_editor):
    BusinessPayoutAccount = apps.get_model("accounts", "BusinessPayoutAccount")

    for acct in BusinessPayoutAccount.objects.all().only(
        "id", "account_name", "account_number"
    ):
        acct.bank_account_name = acct.account_name or ""
        acct.bank_account_number = acct.account_number or ""
        acct.save(update_fields=["bank_account_name", "bank_account_number"])


def reverse_copy_old_bank_fields(apps, schema_editor):
    BusinessPayoutAccount = apps.get_model("accounts", "BusinessPayoutAccount")

    for acct in BusinessPayoutAccount.objects.all().only(
        "id", "bank_account_name", "bank_account_number"
    ):
        acct.account_name = acct.bank_account_name or ""
        acct.account_number = acct.bank_account_number or ""
        acct.save(update_fields=["account_name", "account_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_business_phone_number_alter_user_phone_number'),
    ]

    operations = [
        # 1️⃣ Add new fields first
        migrations.AddField(
            model_name='businesspayoutaccount',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businesspayoutaccount',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businesspayoutaccount',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businesspayoutaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

        # 2️⃣ Copy existing data
        migrations.RunPython(copy_old_bank_fields, reverse_copy_old_bank_fields),

        # 3️⃣ Remove old fields after copy
        migrations.RemoveField(
            model_name='businesspayoutaccount',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='businesspayoutaccount',
            name='account_number',
        ),

        # 4️⃣ Alter bank_code
        migrations.AlterField(
            model_name='businesspayoutaccount',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),

        # 5️⃣ Ensure table name
        migrations.AlterModelTable(
            name='businesspayoutaccount',
            table='accounts_businesspayoutaccount',
        ),
    ]