# Generated by Django 5.1 on 2026-04-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_remove_businesspayoutaccount_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryagent',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
