# Generated by Django 5.1 on 2026-04-20 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_primaryagent_revoked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryagent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
