# Generated by Django 5.1 on 2026-04-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_primaryagent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryagent',
            name='device_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='primaryagent',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked', False)), fields=('device_name',), name='unique_active_device'),
        ),
    ]
