# Generated by Django 5.1 on 2026-05-01 16:08

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_alter_primaryagent_device_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscerd',
            name='business_doc',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(bucket_name='ovena-delivery-private-bucket', custom_domain=None, file_overwrite=False, location='private', querystring_auth=True), upload_to='business/docs/'),
        ),
    ]
