# Generated by Django 5.1 on 2026-05-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alter_businesscerd_business_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='business/logos/'),
        ),
    ]
