# Generated by Django 5.1 on 2026-05-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_user_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='rating',
        ),
        migrations.AddField(
            model_name='business',
            name='avg_rating',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='business',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
    ]
