# Generated by Django 5.1 on 2026-06-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_customerprofile_pickup_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryagent',
            name='name',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
