# Generated by Django 5.1 on 2026-06-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_primaryagent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspayoutaccount',
            name='bank_card_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspayoutaccount',
            name='bank_card_info',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
