# Generated by Django 5.1 on 2026-06-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_businesspayoutaccount_bank_card_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspayoutaccount',
            name='bank_card_expiry_date',
        ),
        migrations.RemoveField(
            model_name='businesspayoutaccount',
            name='bank_card_info',
        ),
        migrations.AddField(
            model_name='businesspayoutaccount',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
