# Generated by Django 5.1 on 2026-06-23 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_remove_businesspayoutaccount_bank_card_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_enabled', models.BooleanField(default=False)),
                ('carousel_enabled', models.BooleanField(default=False)),
                ('banner_info', models.JSONField(blank=True, default=dict, null=True)),
                ('carousel_image', models.ImageField(blank=True, null=True, upload_to='business/carousel/')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.business')),
            ],
        ),
    ]
