# Generated by Django 5.1 on 2026-07-12 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_businesssubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], db_index=True, max_length=20)),
                ('provider_uid', models.CharField(max_length=255)),
                ('email_at_signup', models.EmailField(blank=True, max_length=254, null=True)),
                ('raw_signup_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'provider'], name='accounts_so_user_id_0a462a_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_uid'), name='uniq_socialaccount_provider_uid')],
            },
        ),
    ]
