# Generated by Django 5.1 on 2026-07-13 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_socialaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverbankaccount',
            old_name='account_number',
            new_name='bank_account_number',
        ),
        migrations.RenameField(
            model_name='driverbankaccount',
            old_name='account_name',
            new_name='bank_account_name',
        ),
        migrations.AlterField(
            model_name='driverbankaccount',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driverbankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverbankaccount',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driverbankaccount',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driverbankaccount',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
