# Generated by Django 5.1 on 2026-07-28 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_rename_account_number_driverbankaccount_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryAgentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('revoked', 'Revoked'), ('reclaimed', 'Reclaimed'), ('unrevoked', 'Unrevoked')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_agent_history', to='accounts.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.businessadmin')),
                ('primary_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='accounts.primaryagent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_agent_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', '-created_at'], name='accounts_pr_branch__bda464_idx'), models.Index(fields=['user', '-created_at'], name='accounts_pr_user_id_6090f9_idx')],
            },
        ),
    ]
