# Generated by Django 5.1 on 2026-10-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_decouple_profilebase_mti'),
        ('referrals', '0005_remove_profilereferral_referee_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileBase',
        ),
    ]
