# Generated by Django 5.1 on 2026-03-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_api', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='driverledgerentry',
            new_name='driver_api__driver__97c8f0_idx',
            old_name='driver_api_d_driver__7d94df_idx',
        ),
        migrations.RenameIndex(
            model_name='driverledgerentry',
            new_name='driver_api__source__96337a_idx',
            old_name='driver_api_d_source__af04ed_idx',
        ),
        migrations.RenameIndex(
            model_name='drivernotification',
            new_name='driver_api__driver__32ecd7_idx',
            old_name='driver_api_d_driver__ee6cd3_idx',
        ),
        migrations.RenameIndex(
            model_name='driverwithdrawalrequest',
            new_name='driver_api__driver__ccab75_idx',
            old_name='driver_api_d_driver__4cf15e_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='driver_api__driver__7911a5_idx',
            old_name='driver_api_s_driver__5f6b7b_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='driver_api__is_bloc_2b272b_idx',
            old_name='driver_api_s_is_blo_9f8a93_idx',
        ),
        migrations.AddField(
            model_name='driverwithdrawalrequest',
            name='payment_withdrawal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_withdrawal', to='payments.withdrawal'),
        ),
    ]
