# Generated by Django 5.1 on 2026-04-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_api', '0002_rename_driver_api_d_driver__7d94df_idx_driver_api__driver__97c8f0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='supportticketmessage',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='DriverNotification',
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
        migrations.DeleteModel(
            name='SupportTicketMessage',
        ),
    ]
