# Generated by Django 5.1 on 2026-03-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_center', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='businesssupportticket',
            new_name='support_cen_busines_e339d6_idx',
            old_name='support_cen_busines_6d3655_idx',
        ),
    ]
