# Generated by Django 5.1 on 2026-03-31 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_center', '0002_rename_support_cen_busines_6d3655_idx_support_cen_busines_e339d6_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssupportticketmessage',
            name='ticket',
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_role', models.CharField(choices=[('driver', 'Driver'), ('business_admin', 'Business Admin'), ('business_staff', 'Business Staff'), ('customer', 'Customer')], max_length=20)),
                ('category', models.CharField(blank=True, default='general', max_length=80)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_blocking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets_central', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('driver', 'Driver'), ('business_admin', 'Business Admin'), ('business_staff', 'Business Staff'), ('customer', 'Customer'), ('support', 'Support'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('attachments_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support_center.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BusinessSupportTicket',
        ),
        migrations.DeleteModel(
            name='BusinessSupportTicketMessage',
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['owner_role', 'status', '-created_at'], name='support_cen_owner_r_cdf9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['owner', 'status', '-created_at'], name='support_cen_owner_i_6ae787_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['is_blocking', 'status'], name='support_cen_is_bloc_53fb78_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_cen_ticket__45f56f_idx'),
        ),
    ]
