# Generated by Django 5.1 on 2026-03-31 16:24

import authflow.services.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_center', '0003_remove_businesssupportticketmessage_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='id',
            field=authflow.services.model.ULIDField(db_index=True, default=authflow.services.model.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supportticketmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='supportticketmessage',
            name='id',
            field=authflow.services.model.ULIDField(db_index=True, default=authflow.services.model.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
    ]
