# Generated by Django 5.1 on 2026-07-18 07:49

import authflow.services.model
import django.core.validators
import django.db.models.deletion
import support_center.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_center', '0005_supportticket_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticketmessage',
            name='attachments_json',
        ),
        migrations.CreateModel(
            name='SupportTicketAttachment',
            fields=[
                ('id', authflow.services.model.ULIDField(db_index=True, default=authflow.services.model.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file', models.ImageField(upload_to=support_center.models.ticket_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'heic'])])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support_center.supportticketmessage')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message', 'created_at'], name='support_cen_message_97c481_idx')],
            },
        ),
    ]
