# Generated by Django 5.1 on 2026-02-10 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0030_alter_branch_restaurant_and_more'),
        ('menu', '0011_remove_baseitem_unique_name_per_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('coupon_type', models.CharField(choices=[('delivery', 'Free-delivery'), ('itemdiscount', 'Amount-off-an-Item'), ('categorydiscount', 'Amount-off-a-category'), ('BxGy', 'Buy-X-Get-Y')], default='delivery', max_length=30)),
                ('buy_amount', models.PositiveIntegerField(default=0)),
                ('get_amount', models.PositiveIntegerField(default=0)),
                ('scope', models.CharField(choices=[('global', 'Platform-wide'), ('restaurant', 'Restaurant-only')], default='restaurant', max_length=20)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('amount', 'Fixed-amount')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='menu.menucategory')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='menu.menuitem')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='accounts.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='CouponWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_entries_amount', models.SmallIntegerField(default=6)),
                ('is_active', models.BooleanField(default=False)),
                ('coupons', models.ManyToManyField(to='coupons_discount.coupons')),
            ],
        ),
    ]
