# Generated by Django 5.1 on 2026-02-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_business_remove_branch_restaurant_alter_user_role_and_more'),
        ('coupons_discount', '0002_add_buy_get_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='coupons',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='accounts.business'),
        ),
    ]
