# Generated by Django 5.1 on 2026-03-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons_discount', '0003_remove_coupons_restaurant_coupons_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='scope',
            field=models.CharField(choices=[('global', 'Platform-wide'), ('business', 'Business-only')], default='business', max_length=20),
        ),
    ]
