# Generated by Django 5.1 on 2026-05-29 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons_discount', '0004_alter_coupons_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='is_reward',
            field=models.BooleanField(default=False, help_text="Reward coupons are awarded via the spin wheel and redeemed through the user's wallet. Marketing coupons are distributed as codes."),
        ),
        migrations.CreateModel(
            name='UserCouponWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_from_wheel_spin', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallets', to='coupons_discount.coupons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_coupon_wallet',
                'indexes': [models.Index(fields=['user', 'is_used'], name='user_coupon_user_id_ad1396_idx'), models.Index(fields=['coupon', 'is_used'], name='user_coupon_coupon__5e519b_idx')],
            },
        ),
    ]
