# Generated by Django 5.1 on 2026-06-02 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons_discount', '0005_coupons_is_reward_usercouponwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
