# Generated by Django 5.1.6 on 2025-08-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_restaurant_remove_restaurantprofile_location_and_more'),
        ('menu', '0002_menu_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_groups', to='menu.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_diff', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.variantgroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitemvariant',
            name='item',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='accounts.restaurant'),
        ),
        migrations.DeleteModel(
            name='MenuItemVariant',
        ),
    ]
