# Generated by Django 5.1.6 on 2025-08-21 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_restaurantprofile'),
        ('menu', '0003_variantgroup_variantoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('override_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_availabilities', to='menu.menuitem')),
            ],
            options={
                'unique_together': {('branch', 'item')},
            },
        ),
    ]
