# Generated by Django 5.1 on 2025-09-08 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_branch_location_and_more'),
        ('menu', '0005_customer_driver_remove_menuitem_is_available_coupons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='base/items/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemavailability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menuitemavailability',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='menuitemavailability',
            name='item',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='custom_name',
        ),
        migrations.RemoveField(
            model_name='menuitemaddon',
            name='group',
        ),
        migrations.RemoveField(
            model_name='menuitemaddon',
            name='name',
        ),
        migrations.AddField(
            model_name='menuitemaddon',
            name='groups',
            field=models.ManyToManyField(related_name='addons', to='menu.menuitemaddongroup'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.customerprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.driverprofile'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='base_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.baseitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitemaddon',
            name='base_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='as_addon', to='menu.baseitem'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BaseItemAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('override_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_availabilities', to='menu.baseitem')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_availabilities', to='accounts.branch')),
            ],
            options={
                'unique_together': {('branch', 'base_item')},
            },
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.baseitemavailability'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='MenuItemAvailability',
        ),
    ]
