# Generated by Django 5.1 on 2025-09-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role_primaryagent_linkedstaff_and_more'),
        ('menu', '0006_baseitem_category_alter_order_orderer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='favorite',
            field=models.ManyToManyField(to='accounts.customerprofile'),
        ),
    ]
