# Generated by Django 5.1 on 2026-02-02 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_branch_avg_rating_branch_rating_count_and_more'),
        ('menu', '0009_address_chatmessage_orderevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='baseitem',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='base_items', to='accounts.restaurant'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='baseitem',
            constraint=models.UniqueConstraint(['restaurant', 'name'], name='unique_name_per_restaurant'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
