# Generated by Django 5.1 on 2026-02-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_branch_avg_rating_branch_rating_count_and_more'),
        ('menu', '0010_remove_address_user_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='baseitem',
            name='unique_name_per_restaurant',
        ),
        migrations.AddConstraint(
            model_name='baseitem',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_name_per_restaurant'),
        ),
    ]
