# Generated by Django 5.1 on 2026-02-10 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons_discount', '0001_initial'),
        ('menu', '0011_remove_baseitem_unique_name_per_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coupons_discount.coupons'),
        ),
        migrations.DeleteModel(
            name='Coupons',
        ),
    ]
