# Generated by Django 5.1 on 2026-02-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_order_coupons_delete_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
