# Generated by Django 5.1 on 2026-02-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_business_remove_branch_restaurant_alter_user_role_and_more'),
        ('menu', '0013_orderitem_snapshot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='baseitem',
            name='unique_name_per_restaurant',
        ),
        migrations.RemoveField(
            model_name='baseitem',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='baseitem',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_items', to='accounts.business'),
        ),
        migrations.AddField(
            model_name='menu',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='accounts.business'),
        ),
        migrations.AddConstraint(
            model_name='baseitem',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_name_per_business'),
        ),
    ]
