# Generated by Django 5.1 on 2026-03-19 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_remove_baseitem_unique_name_per_restaurant_and_more'),
        ('payments', '0002_useraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='payments.sale'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
