# Generated by Django 5.1 on 2026-03-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_remove_user_role'),
        ('menu', '0015_remove_order_payment_order_sale_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitemavailability',
            name='base_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_availabilities', to='menu.baseitem'),
        ),
        migrations.AlterField(
            model_name='baseitemavailability',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_availabilities', to='accounts.branch'),
        ),
    ]
