# Generated by Django 5.1 on 2026-04-11 11:19
from decimal import Decimal
from django.db import migrations, models


def populate_items_total(apps, schema_editor):
    Order = apps.get_model("menu", "Order")

    for order in Order.objects.all().only("id", "subtotal", "discount_total"):
        subtotal = order.subtotal or Decimal("0")
        discount = order.discount_total or Decimal("0")

        order.items_total = subtotal - discount
        order.save(update_fields=["items_total"])


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0016_alter_baseitemavailability_base_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="items_total",
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                default=0
            ),
        ),
        migrations.RunPython(populate_items_total),
    ]