# Generated by Django 5.1 on 2026-05-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_order_items_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_number',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
    ]
