# Generated by Django 5.1 on 2026-05-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_order_driver_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
