# Generated by Django 5.1 on 2026-06-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='picked_up_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
