# Generated by Django 5.1 on 2026-07-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_order_last_payment_attempt_order_next_retry_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='addtional_note',
            field=models.TextField(default=''),
        ),
    ]
