# Generated by Django 5.1 on 2026-08-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_remove_order_payment_shadow_fields'),
        ('payments', '0016_sale_payment_source_sale_responsible_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='payments.sale'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment_method', 'Awaiting Payment Method'), ('payment_pending', 'Payment Pending'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('driver_assigned', 'Driver Assigned'), ('picked_up', 'Picked Up'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('payment_initialization_failed', 'Payment Initialization Failed')], default='payment_pending', max_length=30),
        ),
    ]
