# Generated by Django 5.1 on 2026-08-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_penalty_suspension_appeal'),
        ('coupons_discount', '0006_coupons_created_at'),
        ('menu', '0026_alter_order_sale_alter_order_status'),
        ('payments', '0016_sale_payment_source_sale_responsible_party_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['orderer', 'status', 'delivered_at'], name='menu_order_orderer_358e99_idx'),
        ),
    ]
