# Generated by Django 5.1 on 2026-08-21 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_order_menu_order_orderer_358e99_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='menucategory',
            name='global_tags',
            field=models.ManyToManyField(blank=True, related_name='menu_categories', to='menu.globaltag'),
        ),
        migrations.AddField(
            model_name='globaltag',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='menu.taggroup'),
        ),
    ]
