# Generated by Django 5.1 on 2026-09-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_alter_taggroup_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='actor_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver'), ('branch', 'Branch'), ('system', 'System'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Order Created'), ('confirmed', 'Branch Confirmed'), ('rejected', 'Branch Rejected'), ('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('preparing', 'Preparing Food'), ('ready', 'Ready for Pickup'), ('driver_searching', 'Searching for Driver'), ('driver_assigned', 'Driver Assigned'), ('driver_rejected', 'Driver Rejected'), ('driver_matching_failed', 'Driver Matching Failed'), ('pickup_delayed', 'Pickup Delayed'), ('picked_up', 'Order Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('admin_override', 'Admin Override')], max_length=50),
        ),
    ]
