# Generated by Django 5.1 on 2026-06-03 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0060_remove_user_name_businessadmin_name_and_more'),
        ('menu', '0020_alter_baseitem_image_alter_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='accounts.customerprofile')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='menu.menuitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'menu_item'), name='unique_customer_menuitem_favorite')],
            },
        ),
    ]
