# Generated by Django 5.1 on 2026-06-06 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_customerprofile_pickup_food'),
        ('customer_api', '0001_initial'),
        ('menu', '0022_order_picked_up_by_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoritemenuitem',
            name='unique_customer_menuitem_favorite',
        ),
        migrations.AddField(
            model_name='favoritemenuitem',
            name='branch',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='accounts.branch'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='favoritemenuitem',
            constraint=models.UniqueConstraint(fields=('customer', 'menu_item', 'branch'), name='unique_customer_menuitem_branch_favorite'),
        ),
    ]
